feat: add aws ssm install snippet
Signed-off-by: Henrik Gerdes <hegerdes@outlook.de>

diff --git a/.gitlab/ci/snippets.yml b/.gitlab/ci/snippets.yml
--- a/.gitlab/ci/snippets.yml
+++ b/.gitlab/ci/snippets.yml
@@ -1,3 +1,28 @@
+.config:
+  # Needs:
+  # id_tokens:
+  #   GITLAB_OIDC_TOKEN:
+  #     aud: https://gitlab.com
+  # variables:
+  #   AWS_DEFAULT_REGION: eu-cental-1
+  #   AWS_PROFILE: aws-gitlab-ci
+  #   AWS_ROLE_SESSION_NAME: "gitlab-runner-${CI_PROJECT_PATH_SLUG}"
+  #   AWS_ROLE_ARN: "arn:aws:iam::${AWS_ACCOUNT}:role/gitlab-ci-my-project-role"
+  aws-oidc-login:
+    - |
+      echo "Setting up aws oidc..." > /dev/null
+      mkdir -p ~/.aws
+      cat > ~/.aws/config <<EOF
+      [profile ${AWS_PROFILE}]
+      region = ${AWS_DEFAULT_REGION}
+      output = json
+      role_arn=${AWS_ROLE_ARN}
+      web_identity_token_file = /tmp/web_identity_token
+      EOF
+      echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
+    - aws --version
+    - aws sts get-caller-identity
+
 .snippets:
   debian-core-tools:
     - |
@@ -557,6 +582,29 @@
         fi
       fi
       aws --version
+  aws-ssm-install:
+    - |
+      # Check if aws ssm plugin is installed
+      if ! command -v session-manager-plugin > /dev/null; then
+        echo "Installing aws ssm plugin"
+        if command -v apk > /dev/null; then
+          apk add --no-cache aws-session-manager-plugin > /dev/null
+        elif command -v dpkg > /dev/null; then
+          if [ "$(uname -m)" = "x86_64" ]; then
+            ARCH=64bit
+          elif [ "$(uname -m)" = "aarch64" ]; then
+            ARCH=arm64
+          else
+            echo "Unknown system arch. Default to amd64"
+          fi
+          curl -sL "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_${ARCH-64bit}/session-manager-plugin.deb" -o /tmp/ssm-plugin.deb
+          dpkg -i /tmp/ssm-plugin.deb
+          rm /tmp/ssm-plugin.deb
+        else
+          echo "ERROR: This platform is currently not supported"
+        fi
+      fi
+      session-manager-plugin --version
   ssh-setup:
     - |
       # Setting up SSH
@@ -588,3 +636,10 @@
         chmod +x /usr/local/bin/docker-credential-ecr-login
       fi
       docker-credential-ecr-login version
+      if [ "${AWS_ECR_CREDENTIAL_HELPER_SKIP_DOCER_CONF:-false}" != "true" ]; then
+        echo "Creating dockers config.json with ecr credsStore"
+        mkdir -p ~/.docker
+        echo "{\"credsStore\":\"ecr-login\"}" > ~/.docker/config.json
+      else
+        echo "Skipping creation of dockers config.json with ecr credsStore"
+      fi
